declare module 'eslint-plugin-import-x'
declare module 'eslint-plugin-simple-import-sort'
declare module 'eslint-plugin-unicorn'
declare module 'eslint-plugin-react-hooks'
declare module '@eslint-react/eslint-plugin'
declare module '@next/eslint-plugin-next'
declare module 'eslint-plugin-unused-imports'
declare module 'eslint-plugin-github'
