declare module 'eslint-plugin-unicorn'
declare module 'eslint-plugin-react-hooks'
declare module 'eslint-plugin-react-refresh'
declare module 'eslint-plugin-react-compiler'
declare module 'eslint-plugin-unused-imports'
